apiVersion: v1
kind: Namespace
metadata:
  name: observability
  labels:
    app.kubernetes.io/part-of: production-ready-platform
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: amp-ingest
  namespace: observability
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::111111111111:role/platform-dev-amp-ingest
