apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - bluegreen-service.yaml

replicas:
  - name: checkout-api
    count: 4

patches:
  - path: ingress-host.yaml
  - path: hpa-prod.yaml
  - path: deployment-prod.yaml

configMapGenerator:
  - name: checkout-api
    behavior: merge
    literals:
      - LOG_LEVEL=info
      - ENVIRONMENT=prod

generatorOptions:
  disableNameSuffixHash: true
